// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7bZ2EAN5GYak9lHcP1Of7YvRBwtTHTWM',
    appId: '1:677070421504:web:a513e1b9ae1b0586b762e5',
    messagingSenderId: '677070421504',
    projectId: 'passwordmanager-b3df6',
    authDomain: 'passwordmanager-b3df6.firebaseapp.com',
    storageBucket: 'passwordmanager-b3df6.appspot.com',
    measurementId: 'G-QJ55SXW546',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwP6QKXLHAvCvwL6VksRzsARuzQG_ecX8',
    appId: '1:677070421504:android:736975dbca1c671ab762e5',
    messagingSenderId: '677070421504',
    projectId: 'passwordmanager-b3df6',
    storageBucket: 'passwordmanager-b3df6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL2yyXvUU-P3dZuJHuQSXkIpol6as0JP0',
    appId: '1:677070421504:ios:fbaa38b598a4151eb762e5',
    messagingSenderId: '677070421504',
    projectId: 'passwordmanager-b3df6',
    storageBucket: 'passwordmanager-b3df6.appspot.com',
    iosClientId: '677070421504-q2juqo18alpuia5hs5vefd11ghurrmc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.passwordManager',
  );
}
